INSERT INTO books (title, author_id, price) VALUES ('To Kill a Mockingbird', 'Harper Lee', 20);
INSERT INTO books (title, author_id, price) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 25);
INSERT INTO books (title, author_id, price) VALUES ('1984', 'George Orwell', 30);
INSERT INTO books (title, author_id, price) VALUES ('Pride and Prejudice', 'Jane Austen', 35);
INSERT INTO books (title, author_id, price) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 40);
INSERT INTO books (title, author_id, price) VALUES ('To Kill a Mockingbird', 'Harper Lee', 45);
INSERT INTO books (title, author_id, price) VALUES ('The Hobbit', 'J.R.R. Tolkien', 50);
INSERT INTO books (title, author_id, price) VALUES ('Harry Potter and the Philosopher''s Stone', 'J.K. Rowling', 55);
INSERT INTO books (title, author_id, price) VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 60);
INSERT INTO books (title, author_id, price) VALUES ('Animal Farm', 'George Orwell', 65);
INSERT INTO books (title, author_id, price) VALUES ('1984', 'George Orwell', 75);
INSERT INTO books (title, author_id, price) VALUES ('To Kill a Mockingbird', 'Harper Lee', 80);
INSERT INTO books (title, author_id, price) VALUES ('The Great Gatsby', 'F. Scott Fitzgerald', 70);
INSERT INTO books (title, author_id, price) VALUES ('Brave New World', 'Aldous Huxley', 68);
INSERT INTO books (title, author_id, price) VALUES ('Moby Dick', 'Herman Melville', 85);
INSERT INTO books (title, author_id, price) VALUES ('War and Peace', 'Leo Tolstoy', 90);
INSERT INTO books (title, author_id, price) VALUES ('The Catcher in the Rye', 'J.D. Salinger', 78);
INSERT INTO books (title, author_id, price) VALUES ('The Lord of the Rings', 'J.R.R. Tolkien', 120);
INSERT INTO books (title, author_id, price) VALUES ('Pride and Prejudice', 'Jane Austen', 60);
INSERT INTO books (title, author_id, price) VALUES ('The Hobbit', 'J.R.R. Tolkien', 95);
INSERT INTO books (title, author_id, price) VALUES ('Ulysses', 'James Joyce', 110);
INSERT INTO books (title, author_id, price) VALUES ('The Odyssey', 'Homer', 65);
INSERT INTO books (title, author_id, price) VALUES ('The Iliad', 'Homer', 70);
INSERT INTO books (title, author_id, price) VALUES ('Crime and Punishment', 'Fyodor Dostoevsky', 85);
INSERT INTO books (title, author_id, price) VALUES ('Great Expectations', 'Charles Dickens', 75);
INSERT INTO books (title, author_id, price) VALUES ('Don Quixote', 'Miguel de Cervantes', 90);
INSERT INTO books (title, author_id, price) VALUES ('The Brothers Karamazov', 'Fyodor Dostoevsky', 88);
INSERT INTO books (title, author_id, price) VALUES ('Les Misérables', 'Victor Hugo', 95);
INSERT INTO books (title, author_id, price) VALUES ('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 85);
INSERT INTO books (title, author_id, price) VALUES ('The Divine Comedy', 'Dante Alighieri', 100);
